version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - 'typescript'
    ignore:
      - dependency-name: typescript
        versions:
          - '>=7'
    commit-message:
      prefix: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: chore
